// Liste des 100 types de commerces partenaires DepXpreS
// Source statique — pas besoin de Firestore pour ces données fixes

export interface CommerceType {
  id: string;
  name: string;
  group: string;
  icon: string;
  priority: "high" | "medium" | "low";
}

export const COMMERCE_TYPES: CommerceType[] = [
  // ── Alimentaire de proximité ─────────────────────────────────────────────
  { id: "001-depanneur", name: "Dépanneur", group: "Alimentaire de proximité", icon: "Store", priority: "high" },
  { id: "002-epicerie-de-quartier", name: "Épicerie de quartier", group: "Alimentaire de proximité", icon: "ShoppingBasket", priority: "high" },
  { id: "003-mini-marche-de-quartier", name: "Mini-marché de quartier", group: "Alimentaire de proximité", icon: "ShoppingCart", priority: "high" },
  { id: "004-fruiterie", name: "Fruiterie", group: "Alimentaire de proximité", icon: "Apple", priority: "high" },
  { id: "005-marchand-de-legumes", name: "Marchand de légumes", group: "Alimentaire de proximité", icon: "Leaf", priority: "medium" },
  { id: "006-boucherie", name: "Boucherie", group: "Alimentaire de proximité", icon: "Beef", priority: "high" },
  { id: "007-charcuterie", name: "Charcuterie", group: "Alimentaire de proximité", icon: "Utensils", priority: "medium" },
  { id: "008-poissonnerie", name: "Poissonnerie", group: "Alimentaire de proximité", icon: "Fish", priority: "medium" },
  { id: "009-boulangerie-artisanale", name: "Boulangerie artisanale", group: "Alimentaire de proximité", icon: "Bread", priority: "high" },
  { id: "010-patisserie", name: "Pâtisserie", group: "Alimentaire de proximité", icon: "Cake", priority: "high" },
  { id: "011-viennoiserie-artisanale", name: "Viennoiserie artisanale", group: "Alimentaire de proximité", icon: "Croissant", priority: "medium" },
  { id: "012-biscuiterie", name: "Biscuiterie", group: "Alimentaire de proximité", icon: "Cookie", priority: "medium" },
  { id: "013-fromagerie", name: "Fromagerie", group: "Alimentaire de proximité", icon: "Cheese", priority: "medium" },
  { id: "014-cremerie", name: "Crèmerie", group: "Alimentaire de proximité", icon: "IceCream", priority: "medium" },
  { id: "015-glacier-artisanal", name: "Glacier artisanal", group: "Alimentaire de proximité", icon: "IceCream2", priority: "high" },
  { id: "016-sorbetier", name: "Sorbetier", group: "Alimentaire de proximité", icon: "Snowflake", priority: "low" },
  { id: "017-chocolaterie", name: "Chocolaterie", group: "Alimentaire de proximité", icon: "Candy", priority: "high" },
  { id: "018-confiserie", name: "Confiserie", group: "Alimentaire de proximité", icon: "CandyOff", priority: "medium" },
  { id: "019-torrefacteur-de-cafe", name: "Torréfacteur de café", group: "Alimentaire de proximité", icon: "Coffee", priority: "high" },
  { id: "020-boutique-de-the", name: "Boutique de thé", group: "Alimentaire de proximité", icon: "Coffee", priority: "medium" },
  { id: "021-boutique-d-epices", name: "Boutique d'épices", group: "Alimentaire de proximité", icon: "Flame", priority: "medium" },
  { id: "022-marchand-de-noix", name: "Marchand de noix et fruits secs", group: "Alimentaire de proximité", icon: "Nut", priority: "medium" },
  { id: "023-magasin-produits-fins", name: "Magasin de produits fins", group: "Alimentaire de proximité", icon: "Star", priority: "medium" },
  { id: "024-epicerie-bio", name: "Épicerie bio", group: "Alimentaire de proximité", icon: "Sprout", priority: "high" },
  { id: "025-magasin-en-vrac", name: "Magasin en vrac", group: "Alimentaire de proximité", icon: "Scale", priority: "medium" },
  { id: "026-marchand-huiles-vinaigres", name: "Marchand d'huiles et vinaigres", group: "Alimentaire de proximité", icon: "Droplets", priority: "low" },
  { id: "027-boutique-miel", name: "Boutique de miel et produits de la ruche", group: "Alimentaire de proximité", icon: "Hexagon", priority: "low" },
  { id: "028-confiturerie-artisanale", name: "Confiturerie artisanale", group: "Alimentaire de proximité", icon: "Jar", priority: "low" },
  { id: "029-fabricant-sauces", name: "Fabricant de sauces et condiments", group: "Alimentaire de proximité", icon: "Flask", priority: "low" },
  { id: "030-fabrique-pates-fraiches", name: "Fabrique de pâtes fraîches", group: "Alimentaire de proximité", icon: "Utensils", priority: "medium" },
  { id: "031-raviolerie", name: "Raviolerie", group: "Alimentaire de proximité", icon: "Utensils", priority: "low" },
  { id: "032-bagelerie-artisanale", name: "Bagelerie artisanale", group: "Alimentaire de proximité", icon: "Circle", priority: "medium" },
  { id: "033-marchand-surgeles-artisanaux", name: "Marchand de produits surgelés artisanaux", group: "Alimentaire de proximité", icon: "Thermometer", priority: "medium" },
  { id: "034-producteur-granola", name: "Producteur de granola et céréales", group: "Alimentaire de proximité", icon: "Wheat", priority: "low" },
  { id: "035-marchand-collations-sante", name: "Marchand de collations santé", group: "Alimentaire de proximité", icon: "Zap", priority: "medium" },
  { id: "036-fabricant-popcorn-gourmet", name: "Fabricant de popcorn gourmet", group: "Alimentaire de proximité", icon: "Star", priority: "low" },
  { id: "037-boutique-kombucha", name: "Boutique de kombucha et boissons artisanales", group: "Alimentaire de proximité", icon: "Bottle", priority: "low" },
  { id: "038-marchand-jus-presses", name: "Marchand de jus pressés embouteillés", group: "Alimentaire de proximité", icon: "Droplet", priority: "medium" },
  { id: "039-magasin-sans-gluten", name: "Magasin de produits sans gluten", group: "Alimentaire de proximité", icon: "Ban", priority: "low" },
  { id: "040-boutique-vegalienne", name: "Boutique végétalienne spécialisée", group: "Alimentaire de proximité", icon: "Leaf", priority: "medium" },
  // ── Beauté, santé et consommation courante ───────────────────────────────
  { id: "041-pharmacie-independante", name: "Pharmacie indépendante", group: "Beauté, santé et consommation courante", icon: "Pill", priority: "high" },
  { id: "042-parapharmacie", name: "Parapharmacie", group: "Beauté, santé et consommation courante", icon: "Heart", priority: "medium" },
  { id: "043-tabagie", name: "Tabagie", group: "Beauté, santé et consommation courante", icon: "Cigarette", priority: "high" },
  { id: "044-boutique-vapotage", name: "Boutique de vapotage", group: "Beauté, santé et consommation courante", icon: "Wind", priority: "medium" },
  { id: "045-herboristerie", name: "Herboristerie", group: "Beauté, santé et consommation courante", icon: "Sprout", priority: "medium" },
  { id: "046-boutique-supplements", name: "Boutique de suppléments", group: "Beauté, santé et consommation courante", icon: "Dumbbell", priority: "medium" },
  { id: "047-boutique-cosmetiques", name: "Boutique de cosmétiques indépendants", group: "Beauté, santé et consommation courante", icon: "Sparkles", priority: "medium" },
  { id: "048-savonnerie-artisanale", name: "Savonnerie artisanale", group: "Beauté, santé et consommation courante", icon: "Droplets", priority: "medium" },
  { id: "049-boutique-produits-corporels", name: "Boutique de produits corporels", group: "Beauté, santé et consommation courante", icon: "HandHeart", priority: "low" },
  { id: "050-magasin-hygiene-naturelle", name: "Magasin de produits d'hygiène naturelle", group: "Beauté, santé et consommation courante", icon: "Leaf", priority: "low" },
  { id: "051-lunetterie-independante", name: "Lunetterie indépendante", group: "Beauté, santé et consommation courante", icon: "Glasses", priority: "medium" },
  { id: "052-boutique-orthopedique", name: "Boutique orthopédique", group: "Beauté, santé et consommation courante", icon: "Activity", priority: "low" },
  { id: "053-magasin-premiers-soins", name: "Magasin de premiers soins", group: "Beauté, santé et consommation courante", icon: "Cross", priority: "low" },
  { id: "054-boutique-parfums-artisanaux", name: "Boutique de parfums artisanaux", group: "Beauté, santé et consommation courante", icon: "Wind", priority: "medium" },
  { id: "055-boutique-zero-dechet", name: "Boutique zéro déchet", group: "Beauté, santé et consommation courante", icon: "Recycle", priority: "medium" },
  // ── Maison et quotidien ───────────────────────────────────────────────────
  { id: "056-fleuriste", name: "Fleuriste", group: "Maison et quotidien", icon: "Flower", priority: "high" },
  { id: "057-jardinerie-de-quartier", name: "Jardinerie de quartier", group: "Maison et quotidien", icon: "TreeDeciduous", priority: "medium" },
  { id: "058-boutique-plantes-interieur", name: "Boutique de plantes d'intérieur", group: "Maison et quotidien", icon: "Flower2", priority: "medium" },
  { id: "059-quincaillerie-de-quartier", name: "Quincaillerie de quartier", group: "Maison et quotidien", icon: "Wrench", priority: "medium" },
  { id: "060-magasin-articles-menagers", name: "Magasin d'articles ménagers", group: "Maison et quotidien", icon: "Home", priority: "medium" },
  { id: "061-boutique-decoration", name: "Boutique de décoration", group: "Maison et quotidien", icon: "Palette", priority: "medium" },
  { id: "062-magasin-literie-textiles", name: "Magasin de literie et textiles maison", group: "Maison et quotidien", icon: "BedDouble", priority: "low" },
  { id: "063-boutique-bougies-senteurs", name: "Boutique de bougies et senteurs maison", group: "Maison et quotidien", icon: "Flame", priority: "medium" },
  { id: "064-boutique-vaisselle-cuisine", name: "Boutique de vaisselle et cuisine", group: "Maison et quotidien", icon: "UtensilsCrossed", priority: "low" },
  { id: "065-magasin-rangement", name: "Magasin de rangement et organisation", group: "Maison et quotidien", icon: "LayoutGrid", priority: "low" },
  { id: "066-boutique-cadeaux", name: "Boutique de cadeaux", group: "Maison et quotidien", icon: "Gift", priority: "high" },
  { id: "067-papeterie", name: "Papeterie", group: "Maison et quotidien", icon: "PenLine", priority: "medium" },
  { id: "068-boutique-cartes-emballages", name: "Boutique de cartes et emballages cadeaux", group: "Maison et quotidien", icon: "MailOpen", priority: "low" },
  { id: "069-magasin-produits-ecologiques", name: "Magasin de produits écologiques maison", group: "Maison et quotidien", icon: "Recycle", priority: "medium" },
  { id: "070-boutique-eclairage-decoratif", name: "Boutique d'éclairage décoratif", group: "Maison et quotidien", icon: "Lightbulb", priority: "low" },
  // ── Mode et accessoires ───────────────────────────────────────────────────
  { id: "071-boutique-vetements", name: "Boutique de vêtements indépendante", group: "Mode et accessoires", icon: "Shirt", priority: "medium" },
  { id: "072-friperie", name: "Friperie", group: "Mode et accessoires", icon: "Recycle", priority: "medium" },
  { id: "073-boutique-mode-locale", name: "Boutique de mode locale", group: "Mode et accessoires", icon: "Sparkles", priority: "medium" },
  { id: "074-magasin-chaussures", name: "Magasin de chaussures", group: "Mode et accessoires", icon: "Footprints", priority: "medium" },
  { id: "075-maroquinerie", name: "Maroquinerie", group: "Mode et accessoires", icon: "Briefcase", priority: "low" },
  { id: "076-bijouterie-independante", name: "Bijouterie indépendante", group: "Mode et accessoires", icon: "Gem", priority: "medium" },
  { id: "077-horlogerie-bijouterie", name: "Horlogerie-bijouterie", group: "Mode et accessoires", icon: "Watch", priority: "low" },
  { id: "078-chapellerie", name: "Chapellerie", group: "Mode et accessoires", icon: "Hat", priority: "low" },
  { id: "079-boutique-accessoires-mode", name: "Boutique d'accessoires de mode", group: "Mode et accessoires", icon: "Glasses", priority: "low" },
  { id: "080-boutique-enfants-bebes", name: "Boutique pour enfants et bébés", group: "Mode et accessoires", icon: "Baby", priority: "medium" },
  // ── Culture, loisirs et niche ─────────────────────────────────────────────
  { id: "081-librairie-independante", name: "Librairie indépendante", group: "Culture, loisirs et niche", icon: "BookOpen", priority: "medium" },
  { id: "082-disquaire", name: "Disquaire", group: "Culture, loisirs et niche", icon: "Disc", priority: "low" },
  { id: "083-boutique-jeux-jouets", name: "Boutique de jeux et jouets", group: "Culture, loisirs et niche", icon: "Gamepad", priority: "medium" },
  { id: "084-boutique-materiel-artiste", name: "Boutique de matériel d'artiste", group: "Culture, loisirs et niche", icon: "Palette", priority: "low" },
  { id: "085-boutique-artisanat-local", name: "Boutique d'artisanat local", group: "Culture, loisirs et niche", icon: "HandMetal", priority: "medium" },
  { id: "086-boutique-souvenirs-montreale", name: "Boutique de souvenirs montréalais", group: "Culture, loisirs et niche", icon: "MapPin", priority: "medium" },
  { id: "087-animalerie-independante", name: "Animalerie indépendante", group: "Culture, loisirs et niche", icon: "Dog", priority: "medium" },
  { id: "088-boutique-velo", name: "Boutique de vélo", group: "Culture, loisirs et niche", icon: "Bike", priority: "low" },
  { id: "089-boutique-sport-quartier", name: "Boutique de sport de quartier", group: "Culture, loisirs et niche", icon: "Trophy", priority: "medium" },
  { id: "090-magasin-telephonie-accessoires", name: "Magasin de téléphonie et accessoires", group: "Culture, loisirs et niche", icon: "Smartphone", priority: "medium" },
  { id: "091-boutique-informatique", name: "Boutique informatique de détail", group: "Culture, loisirs et niche", icon: "Monitor", priority: "low" },
  { id: "092-boutique-photo", name: "Boutique photo", group: "Culture, loisirs et niche", icon: "Camera", priority: "low" },
  { id: "093-boutique-chasse-peche", name: "Boutique de chasse et pêche", group: "Culture, loisirs et niche", icon: "Crosshair", priority: "low" },
  { id: "094-boutique-esoterique", name: "Boutique ésotérique", group: "Culture, loisirs et niche", icon: "Stars", priority: "low" },
  { id: "095-magasin-religieux", name: "Magasin religieux spécialisé", group: "Culture, loisirs et niche", icon: "BookMarked", priority: "low" },
  { id: "096-boutique-fetes", name: "Boutique de fêtes", group: "Culture, loisirs et niche", icon: "PartyPopper", priority: "medium" },
  { id: "097-boutique-saisonniere", name: "Boutique saisonnière", group: "Culture, loisirs et niche", icon: "Calendar", priority: "medium" },
  { id: "098-kiosque-journaux-loterie", name: "Kiosque de journaux et loterie", group: "Culture, loisirs et niche", icon: "Newspaper", priority: "medium" },
  { id: "099-boutique-produits-locaux-qc", name: "Boutique de produits locaux québécois", group: "Culture, loisirs et niche", icon: "MapPin", priority: "high" },
  { id: "100-magasin-multi-produits", name: "Magasin multi-produits de quartier", group: "Culture, loisirs et niche", icon: "Store", priority: "high" },
];

// Retourner les groupes uniques dans l'ordre
export const COMMERCE_TYPE_GROUPS = Array.from(new Set(COMMERCE_TYPES.map(c => c.group)));
